language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t n4vdeep/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true n4vdeep/docker-react npm run test
