language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t n4vdeep/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true n4vdeep/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-nd"
  env: "Dockerreactnd-env"
  bucket_name: "elasticbeanstalk-eu-west-2-269858393284"
  bucket_path: "docker-react-nd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  